// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using SGEEP.Infrastructure.Data;

#nullable disable

namespace SGEEP.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260316000000_AddDiretorCursoProfessor")]
    partial class AddDiretorCursoProfessor
    {
    }
}
